eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  datasource:
    username: admin
    password: admin123

logging:
  level:
    root: INFO

management:
  tracing:
    sampling:
      probability: 1.0 # 1.0 = 100% de las peticiones (para desarrollo)
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

# Configuración personalizada para Secrets Manager
aws:
  secretsmanager:
    endpoint: http://localhost:4566
    region: us-east-1
    enabled: true

# Secrets que se cargarán
secrets:
  database: prod/security/database
  jwt: prod/security/jwt
  external-apis: prod/external/api-keys
  cache: prod/cache/redis
